/**
 * @fileoverview gRPC-Web generated client stub for job
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: job.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as job_pb from './job_pb'; // proto import: "job.proto"


export class JobServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStartJob = new grpcWeb.MethodDescriptor(
    '/job.JobService/StartJob',
    grpcWeb.MethodType.SERVER_STREAMING,
    job_pb.JobRequest,
    job_pb.JobUpdate,
    (request: job_pb.JobRequest) => {
      return request.serializeBinary();
    },
    job_pb.JobUpdate.deserializeBinary
  );

  startJob(
    request: job_pb.JobRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<job_pb.JobUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/job.JobService/StartJob',
      request,
      metadata || {},
      this.methodDescriptorStartJob);
  }

  methodDescriptorWatchJobs = new grpcWeb.MethodDescriptor(
    '/job.JobService/WatchJobs',
    grpcWeb.MethodType.SERVER_STREAMING,
    job_pb.Empty,
    job_pb.JobUpdate,
    (request: job_pb.Empty) => {
      return request.serializeBinary();
    },
    job_pb.JobUpdate.deserializeBinary
  );

  watchJobs(
    request: job_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<job_pb.JobUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/job.JobService/WatchJobs',
      request,
      metadata || {},
      this.methodDescriptorWatchJobs);
  }

}

